<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>shader</string>
	</array>
	<key>name</key>
	<string>Unity Shader</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(unity_ObjectToWorld|UNITY_LIGHTMODEL_AMBIENT|(_LightColor)[0-1])</string>
			<key>name</key>
			<string>grand</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>function</string>
			<key>match</key>
			<string>(UnityObjectToClipPos|UnityObjectToWorldNormal|ObjSpaceLightDir|ObjSpaceViewDir|sqrt)</string>
			<key>name</key>
			<string>function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(POSITION|SV_POSITION|SV_Target|NORMAL|TANGENT|TEXCOORD0|TEXCOORD1|TEXCOORD2|TEXCOORD3|TEXCOORD4|TEXCOORD5)</string>
			<key>name</key>
			<string>default</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(CGPROGRAM)</string>
			<key>name</key>
			<string>organization</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(ENDCG)</string>
			<key>name</key>
			<string>organization</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(Sub)?Shader|pass|Category|SeparateSpecular|Fog|Material|ColorMaterial|Name|Properties|CGINCLUDE|FallBack|Tags|LOD|Cull|Blend|AlphaTest|ColorMask|Lighting|ZWrite|BindChannels|Pass|return</string>
			<key>name</key>
			<string>organization</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>annotate</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Types</string>
			<key>match</key>
			<string>(?&lt;=[, \s\(\)])(((float|half|fixed)[2-4]?)|(float|half|fixed)[2-4]x[2-4]|SurfaceOutput|inout|bool|sampler(CUBE|[23]D)|void|2D|Color|struct|[Ff]loat)(?=[,\s\(\)])</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>\"[^\"]*\"</string>
			<key>name</key>
			<string>char</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>annotate</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>annotate</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>compiler directive</string>
			<key>match</key>
			<string>(#)(pragma|include|ifdef|endif|if|define).*</string>
			<key>name</key>
			<string>meta.preprocessor.source.shader</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>functions</string>
			<key>match</key>
			<string>(length|cross|pow|tex2D|UnpackNormal|saturate|dot|normalize|clip|frac|mul|TRANSFORM_TEX|Bind|SetTexture|matrix|constantColor|combine|UnityPixelSnap)</string>
			<key>name</key>
			<string>function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>number literals</string>
			<key>match</key>
			<string>\b([-+]?([0-9]+(\.[0-9]+)?|\.[0-9]+)[\s]*,[\s]*)*([-+]?([0-9]+(\.[0-9]+)?|\.[0-9]+)[fF]?)+\b</string>
			<key>name</key>
			<string>value</string>
		</dict>

	</array>
	<key>scopeName</key>
	<string>source.shader</string>
	<key>uuid</key>
	<string>e3872ec7-60d7-4cc2-bf8f-57da56c339f2</string>
</dict>
</plist>
